### PR TITLE
new frame type, movingplatform and manual control now have different frames

### PR DESCRIPTION
**Pull request by verae98**
moving platform and manual control do now have different frames for RobOS

### CODE REVIEW

**Comment by itzandroidtab** [comment]
Is there a special reason to have a duplicate frame? Can't they reuse the other frame?

**Comment by YouriOkkerse** [comment]
@itzandroidtab RobOS has been introduced. "frame_manual_control_s" will be recieved by RobOS from manual control module. RobOS then takes all the data from this frame, drops it into "frame_movement_conrtol". RobOS then send the "frame_movement_conrtol" to moving platfrom module. If there would only be one frame_type they would be communicating directly instead of via RobOS.

**Comment by LRstudentHU** [comment]
Technically, we could reuse the same struct but simply create a new enumeration value.

**Comment by itzandroidtab** [comment]
The idea of @LRstudentHU is probably be the best idea for now. No need for a totaly new struct if we can reuse the other one with a new enum value added.

**Comment by verae98** [comment]
We do need it if we will expand our functions. Maybe moving platform want a new variable in the struct with a second turn function (turning slowly for manual control and turning an exact degrees for voice interaction) This way, we don't get code issues that a variable is new and not filled by the other party. With this fiew, i made a new struct

**Comment by LRstudentHU** [comment]
Fair enough. Please update the branch against master and add `R2D2_PACK_STRUCT` between the struct and the comment (as with other frame types)

**Review by LRstudentHU — APPROVED** [review]

**Pull request merged**
