### PR TITLE
changed distance frame

### PR DESCRIPTION
**Pull request by Gian1080**
Added my frame type for distance in cm from sonar (HC-SR04).

### CODE REVIEW

**Comment by itzandroidtab** [comment]
What is the difference between this frame and the other distance frame?

**Comment by Gian1080** [comment]
The other frame is from the lidar and I prefer to keep these sensors separate.

**Comment by itzandroidtab** [comment]
I talked about it with a lead and he said that we shouldn't differentiate between the different distance sensors. The module has to return a distance and that's all.

**Comment by Gian1080** [comment]
Well, the lidar frame is going to be adjusted and they are inheritly different from eachother. So I suggest that you keep people happy and accept the frame, thanks

**Comment by LRstudentHU** [comment]
Hi @Gian1080,

The leads have discussed this matter; we'd like to see a single distance frame type for the different sensors. That way, RobOS only has to process a single frame.

This is an example of what we had in mind:
```cpp
struct frame_distance_s {
    uint8_t sensor_type; // This is a user defined enumeration
    uint16_t sensor_pov; // The POV the sensor works at
    
    uint8_t count; // The amount of values that are sent (max 55)
    uint16_t angles[55];
    uint16_t values[55];
};
```

If you have more than 55 values (for the Lidar for example), you can send multiple frames and adjust the angle. If you have any questions, please send me a message on Telegram.

**Comment by Gian1080** [comment]
Ok, I will make work of it

**Review by LRstudentHU — CHANGES_REQUESTED** [review]
Looks good, but could you add the array optimisation to the `values` member? Please look at the other frame types for examples.

**Review by PatrickDekker98 — APPROVED** [review]
looks good

**Review by LRstudentHU — APPROVED** [review]

**Pull request merged**
