### PR TITLE
Added working get_data and has_data for mock_bus

### PR DESCRIPTION
**Pull request by jasperdewinther**

### CODE REVIEW

**Comment by LRstudentHU** [comment]
A frame cannot receive a request from itself.

**Comment by jasperdewinther** [comment]
@LRstudentHU How do i request a frame in a test then?

**Comment by LRstudentHU** [comment]
Look at the `Mock bus provides data` tests; in your test change ` const auto frame = comm.create_frame<frame_type::BUTTON_STATE>({true});` to 

```cpp
auto frame = comm.create_frame<frame_type::YOUR_FRAME_TYPE>(...);
frame.request = true;
```

**Comment by jasperdewinther** [comment]
@LRstudentHU Thanks

**Pull request closed without merging**
